# Generated by Django 5.2.6 on 2025-09-20 15:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('cpf_cnpj', models.CharField(max_length=20, unique=True, verbose_name='CPF/CNPJ')),
                ('email', models.EmailField(blank=True, max_length=100, null=True, unique=True)),
                ('telefone', models.CharField(blank=True, max_length=20, null=True)),
                ('endereco', models.CharField(blank=True, max_length=255, null=True)),
                ('idade', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Pessoa',
                'verbose_name_plural': 'Pessoas',
            },
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('pessoa', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='usuarios.pessoa')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('pessoa', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='usuarios.pessoa')),
                ('senha_hash', models.CharField(max_length=255)),
                ('perfil', models.CharField(choices=[('ADMIN', 'Administrador'), ('ANALISTA', 'Analista'), ('VENDEDOR', 'Vendedor'), ('SISTEMA', 'Sistema')], max_length=50)),
            ],
        ),
    ]
