# Generated by Django 5.2.6 on 2025-09-25 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pessoa',
            name='lead_score',
            field=models.IntegerField(default=5, verbose_name='Pontuação do Lead'),
        ),
    ]
