# Generated by Django 5.2.6 on 2025-09-25 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_pessoa_lead_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='classificacao',
            field=models.CharField(choices=[('ALTO', 'Potencial Alto'), ('PADRAO', 'Potencial Padrão'), ('N/A', 'Não Classificado')], default='N/A', max_length=10, verbose_name='Classificação de Potencial'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='situacao',
            field=models.CharField(choices=[('NOVO', 'Novo Contato'), ('NEGOCIANDO', 'Em Negociação'), ('VENDIDO', 'Venda Realizada'), ('PERDIDO', 'Perdido')], default='NOVO', max_length=10, verbose_name='Situação do Atendimento'),
        ),
    ]
